---
name: 'Deploy to Prod'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

env:
  DOKKU_REMOTE_URL: 'ssh://dokku@de01.net.dicebear.com:22/api'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
