---
name: 'Deploy to Pull Server'

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.DOKKU_REMOTE_URL }}/api
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

      - name: Purge CDN Cache
        run: |
          curl --request POST \
            --url https://api.bunny.net/pullzone/${{ vars.CDN_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_KEY }}'